revivl/src/Entity/Promo.php
<?php

namespace App\Entity;

use App\Helper\Status\PromoStatus;
use App\Helper\Status\StatusTrait;
use App\Repository\PromoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\PersistentCollection;

#[ORM\Entity(repositoryClass: PromoRepository::class)]
class Promo
{
    use StatusTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\OneToMany(targetEntity: Promocode::class, mappedBy: 'promo')]
    private $promocodes;

    public function __construct()
    {
        $this->status = PromoStatus::ACTIVE->value;
        $this->promocodes = new PersistentCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStatusName(): string
    {
        return  PromoStatus::from($this->getStatus())->getName();
    }

    public function getPromocodes(): PersistentCollection
    {
        return $this->promocodes;
    }

}

revivl/src/Form/PromoType.php
<?php

namespace App\Form;

use App\Entity\Promo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PromoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Promo::class,
        ]);
    }
}

revivl/src/Controller/Lk/Admin/PromoController.php
<?php

namespace App\Controller\Lk\Admin;

use App\Entity\Promo;
use App\Form\PromoType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/lk/admin/promo')]
#[IsGranted('ROLE_ADMIN')]
class PromoController extends AbstractController
{
    #[Route('', name: 'lk_admin_promo_index', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $promos = $entityManager
            ->getRepository(Promo::class)
            ->findAll();
        /** @var Promo $promo */
        foreach ($promos as $promo) {
            $n = $promo->getStatusName();
        }

        return $this->render('promo/index.html.twig', [
            'promos' => $promos,
        ]);
    }

    #[Route('/new', name: 'lk_admin_promo_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $promo = new Promo();
        $form = $this->createForm(PromoType::class, $promo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($promo);
            $entityManager->flush();

            return $this->redirectToRoute('lk_admin_promo_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('promo/new.html.twig', [
            'promo' => $promo,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'lk_admin_promo_show', methods: ['GET'])]
    public function show(Promo $promo): Response
    {
        return $this->render('promo/show.html.twig', [
            'promo' => $promo,
        ]);
    }

    #[Route('/{id}/edit', name: 'lk_admin_promo_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Promo $promo, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PromoType::class, $promo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('lk_admin_promo_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('promo/edit.html.twig', [
            'promo' => $promo,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'lk_admin_promo_delete', methods: ['POST'])]
    public function delete(Request $request, Promo $promo, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$promo->getId(), $request->request->get('_token'))) {
            $entityManager->remove($promo);
            $entityManager->flush();
        }

        return $this->redirectToRoute('lk_admin_promo_index', [], Response::HTTP_SEE_OTHER);
    }
}

revivl/templates/promo/_delete_form.html.twig
<form method="post" action="{{ path('lk_admin_promo_delete', {'id': promo.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ promo.id) }}">
    <button class="btn">Delete</button>
</form>

revivl/templates/promo/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

revivl/templates/promo/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Promo{% endblock %}

{% block body %}
    <h1>Edit Promo</h1>

    {{ include('promo/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('lk_admin_promo_index') }}">back to list</a>

    {{ include('promo/_delete_form.html.twig') }}
{% endblock %}

revivl/templates/promo/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promo index{% endblock %}

{% block body %}
    <h1>Promo index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Status</th>
                <th>Codes quantity</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for promo in promos %}
            <tr>
                <td>{{ promo.id }}</td>
                <td>{{ promo.name }}</td>
                <td>{{ promo.statusName }}</td>
                <td>{{ promo.promocodes|length }}</td>
                <td>
                    <a href="{{ path('lk_admin_promo_show', {'id': promo.id}) }}">show</a>
                    <a href="{{ path('lk_admin_promo_edit', {'id': promo.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('lk_admin_promo_new') }}">Create new</a>
{% endblock %}

revivl/templates/promo/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Promo{% endblock %}

{% block body %}
    <h1>Create new Promo</h1>

    {{ include('promo/_form.html.twig') }}

    <a href="{{ path('lk_admin_promo_index') }}">back to list</a>
{% endblock %}

revivl/templates/promo/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promo{% endblock %}

{% block body %}
    <h1>Promo</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ promo.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ promo.name }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('lk_admin_promo_index') }}">back to list</a>

    <a href="{{ path('lk_admin_promo_edit', {'id': promo.id}) }}">edit</a>

    {{ include('promo/_delete_form.html.twig') }}
{% endblock %}